# Generated by Django 3.0.5 on 2020-10-27 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20201022_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_shares', models.IntegerField()),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('symbol', models.ForeignKey(default='AGL', on_delete=django.db.models.deletion.CASCADE, to='stocks.ListedEquities')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_summary',
                'managed': True,
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
