# Generated by Django 3.1.3 on 2020-11-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_portfoliosummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosummary',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='portfoliosummary',
            name='current_market_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='portfoliosummary',
            name='total_gain_loss',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosummary',
            name='book_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosummary',
            name='market_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterModelTable(
            name='portfoliosummary',
            table='portfolio_summary',
        ),
    ]
