# Generated by Django 3.1.3 on 2020-11-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20201103_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliosummary',
            old_name='book_value',
            new_name='book_cost',
        ),
    ]
