# Generated by Django 3.1.3 on 2020-11-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20201104_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliosummary',
            old_name='num_shares',
            new_name='shares_remaining',
        ),
    ]
