# Generated by Django 3.0.5 on 2020-10-22 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotransactions',
            name='symbol',
            field=models.ForeignKey(default='AGL', on_delete=django.db.models.deletion.CASCADE, to='stocks.ListedEquities'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliotransactions',
            unique_together={('user', 'date', 'symbol', 'num_shares')},
        ),
    ]
