# Generated by Django 3.1.3 on 2020-11-04 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20201103_2153'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfoliosummary',
            table='portfolio_summary',
        ),
    ]
