# Generated by Django 3.1.3 on 2020-11-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_auto_20201104_0737'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfoliotransactions',
            unique_together={('user', 'date', 'symbol', 'num_shares', 'bought_or_sold')},
        ),
    ]
