# Generated by Django 3.1.4 on 2021-06-14 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0010_auto_20201104_2209"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDividendYield",
            fields=[
                ("yield_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(verbose_name="Date Yield Calculated")),
                (
                    "dividend_yield",
                    models.DecimalField(
                        decimal_places=5, max_digits=20, verbose_name="Yield %"
                    ),
                ),
            ],
            options={
                "db_table": "historical_dividend_yield",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StockNewsData",
            fields=[
                ("news_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(verbose_name="Date")),
                ("title", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=500)),
                ("category", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "stock_news_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PortfolioSectors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_cost",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "market_value",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "total_gain_loss",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                ("sector", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DividendYield",
        ),
        migrations.AlterModelTable(
            name="fundamentalanalysissummary",
            table="calculated_fundamental_ratios",
        ),
    ]
