# Generated by Django 3.1.4 on 2021-06-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_auto_20210614_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliosummary',
            options={'managed': False},
        ),
    ]
