# Generated by Django 3.1.4 on 2021-06-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_auto_20210614_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioSectors',
        ),
    ]
