# Generated by Django 3.1.4 on 2021-06-14 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_delete_portfoliosectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100)),
                ('book_cost', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_gain_loss', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
