# Generated by Django 3.1.4 on 2021-06-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_portfoliosectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosectors',
            name='gain_loss_percent',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='portfoliosummary',
            name='gain_loss_percent',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
