# Generated by Django 3.1.4 on 2021-06-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_auto_20210618_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatorgames',
            name='game_code',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simulatorgames',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='simulatorgames',
            unique_together={('game_code', 'game_name')},
        ),
    ]
