# Generated by Django 3.1.4 on 2021-06-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_auto_20210619_1825'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='simulatorgames',
            unique_together=set(),
        ),
    ]
