# Generated by Django 3.1.4 on 2021-06-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_auto_20210625_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulatorgames',
            name='game_code',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
