# Generated by Django 3.1.4 on 2021-06-25 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_auto_20210625_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulatorplayers',
            name='simulator_game',
            field=models.ForeignKey(db_column='game_name', on_delete=django.db.models.deletion.CASCADE, to='stocks.simulatorgames'),
        ),
    ]
