# Generated by Django 3.1.4 on 2021-07-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_simulatorportfoliosectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatorgames',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simulatorgames',
            name='num_players',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='simulatorplayers',
            name='current_position',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='simulatorplayers',
            name='overall_gain_loss',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='simulatorplayers',
            name='overall_gain_loss_percent',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
