# Generated by Django 3.1.4 on 2021-07-20 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0024_auto_20210719_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulatorgames',
            name='num_players',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simulatorplayers',
            name='simulator_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.simulatorgames'),
        ),
    ]
