# Generated by Django 3.1.4 on 2021-08-12 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0026_simulatorplayers_current_portfolio_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredStocks',
            fields=[
                ('monitored_stock_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('symbol', models.ForeignKey(db_column='symbol', default='AGL', on_delete=django.db.models.deletion.CASCADE, to='stocks.listedequities')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
