# Generated by Django 3.2.18 on 2023-09-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0029_auto_20221219_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawAnnualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=6)),
                ('year_end_date', models.DateField()),
                ('reports_and_statements_referenced', models.CharField(blank=True, max_length=200, null=True)),
                ('total_assets', models.IntegerField(null=True)),
                ('share_capital', models.IntegerField(null=True)),
                ('total_liabilities', models.IntegerField(null=True)),
                ('net_income', models.IntegerField(null=True)),
                ('operating_profit', models.IntegerField(null=True)),
                ('profit_after_tax', models.IntegerField(null=True)),
                ('basic_earnings_per_share', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('total_shareholders_equity', models.IntegerField(null=True)),
                ('total_dividends_paid', models.IntegerField(null=True)),
                ('cash_cash_equivalents', models.IntegerField(null=True)),
                ('total_shares_outstanding', models.IntegerField(null=True)),
                ('dividends_per_share', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'raw_annual_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawQuarterlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=6)),
                ('quarter_end_date', models.DateField()),
                ('reports_and_statements_referenced', models.CharField(blank=True, max_length=200, null=True)),
                ('total_assets', models.IntegerField(null=True)),
                ('share_capital', models.IntegerField(null=True)),
                ('total_liabilities', models.IntegerField(null=True)),
                ('net_income', models.IntegerField(null=True)),
                ('operating_profit', models.IntegerField(null=True)),
                ('profit_after_tax', models.IntegerField(null=True)),
                ('basic_earnings_per_share', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('total_shareholders_equity', models.IntegerField(null=True)),
                ('total_dividends_paid', models.IntegerField(null=True)),
                ('cash_cash_equivalents', models.IntegerField(null=True)),
                ('total_shares_outstanding', models.IntegerField(null=True)),
                ('dividends_per_share', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'raw_quarterly_data',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='summarizeddividendyield',
            name='symbol',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='stocks.listedequities'),
        ),
    ]
